# Generated by Django 3.0.2 on 2020-01-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200103_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='show_summary',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='', max_length=350, unique=True),
        ),
    ]
